### ISSUE TITLE
Iron Golem stacking up on server restart

### ISSUE THREAD

**Issue by hsombini** [SupaHam/NPCs#1]
Hello, 

I got one problem, it's an Iron Golem, everytime the Server reboots gracefully, there's a chance that the Iron Golem remains spawned and a new Iron Golem NPC is spawned on the exactly same location, also invulnerable

Take a closer look on the name of the NPC, it's black because there's alot of NPC duplicated
http://i.imgur.com/x4zgz6J.png

They became so much that it's difficult to click and execute the command on the original NPC

Can you help me track down this issue? I'm using 1.8.8

**Comment by SupaHam** [comment]
Hey,

Thanks for reporting this issue. I'm aware of it and have been for some time. I've never figured out the best way to fix this problem, but I would recommend you use a more stable NPC plugin other than mine. Until now I haven't set an out of date notice, but I will be doing that as I'm unable to invest time into this plugin.

Sorry

EDIT: To kill invulnerable mobs you can use `/minecraft:kill`

`/minecraft:kill @e[type=iron_golem,r=15]` will kill all Iron Golems within a 15 block radius.
